### ISSUE TITLE
Feedback: Exercise 1

### ISSUE THREAD

**Issue by jakobnissen** [FSGade/julia_course#1]
In general, it's really good. I would recommend that you put each exercise in a function, though. Functions are even more fundamental in Julia than in Python. Being enclosed in a function is also a necessity for Julia code to be fast. Most importantly, writing functions help the programmer, because it forces them to split up the problem in smaller parts.

* Ex 1.1 - 1.8: Nice. I especially like the simple solution to ex. 1.8.
* 1.9: A few issues here. First, your algorithm loops over the entire array for every input number. That means, if there are 100 numbers in the array, the first number is accessed 100 times, when it only needs to be accessed once. So it scales `O(N^2)` instead of `O(N)`. Second, you should almost never use the `global` statement. Instead, just use functions. I would write it like this (using functions and no global state):
```
function get_number()
    println("Enter a number")
    parse(Int64, chomp(readline()))
end

function ask_increasing()
    smaller = get_number()
    bigger = smaller
    while bigger ≥ smaller
        smaller, bigger = bigger, get_number()
    end
end
```
1.10: You should probably annotate `n` to be `Integer`, not `Int64` (since it would also work with, e.g. `UInt32`).

1.11: That's very elegant, good job! In this particular case, splatting (that is, unpacking an argument using `...`) does not scale to thousands of elements due to a limit of the Julia compiler. You could circumvent this by doing `tozero(x) = sum(1:abs(x)) * sign(x)`, i.e. by using `sum`. Of course, you had no way of knowing that.

**Comment by FSGade** [comment]
Thank you for the feedback! 
When starting the exercises, I actually thought about using functions, because of what I had read about improving performance in the documentation. I refrained from doing so, as this is usually not part of the exercises in Python, but I do understand that it is necessary for Julia, which I will try to accommodate from now on.

1.9 is definitely not my proudest moment, but more like trying out the `global` statement and `while` loop. It is clear that your solution is superior, and I will try to think more about how my runtime scales.

1.10: Would it be correct to say that one should always use the supertype of all the different types that are applicable for the function when declaring the arguments? And does Julia optimise the code if it turns out only one subtype is used during runtime?

1.11: It does make sense that the splat notation does not scale (like `*` unpacking in Python), but the `sum` function is definitely useful!

**Comment by jakobnissen** [comment]
> 1.10: Would it be correct to say that one should always use the supertype of all the different types that are applicable for the function when declaring the arguments? And does Julia optimise the code if it turns out only one subtype is used during runtime?

People disagree on whether you should annotate your function arguments. The advantage is that it makes the code easier to read, and it makes it easier and quicker to catch bugs, because, as soon as you pass in an unexpected value type, your code will error. The disadvantage is that it's not always possible to predict which types your code will *actually* end up using, especially considering that users can create their own types. And if you have an entire codebase that assumes that something is, say, an `Integer`, and then you pass in your own type and everything crashes for no good reason, that is extremely annoying.

My view is that you should NOT annotate function arguments if the argument could be of a user-defined type. But for internal functions, where you *ought* to know exactly which values are passed in, you should annotate them to the thing that makes sense, i.e. `Integer`, `AbstractSet` etc.

And yes, there is no performance difference whether you annotate or not, or how precisely you annotate. The code will be fully opimized for the type that is *actually* being passed in in all cases.
